# permissions for end users to view calculators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: calculator-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: calculator-operator
    app.kubernetes.io/part-of: calculator-operator
    app.kubernetes.io/managed-by: kustomize
  name: calculator-viewer-role
rules:
- apiGroups:
  - my.domain
  resources:
  - calculators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - my.domain
  resources:
  - calculators/status
  verbs:
  - get
